language: scala
scala:
  - 2.10.4
jdk:
  - openjdk6
sudo: false
cache:
  directories:
    - $HOME/.ivy2
env:
  - HADOOP_VERSION="1.0.4"
  - HADOOP_VERSION="1.2.1"
  - HADOOP_VERSION="2.2.0"
script:
  - sbt -Dhadoop.version=$HADOOP_VERSION test
